# Generated by Django 3.2.8 on 2021-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nume', models.CharField(max_length=255, null=True)),
                ('Prenume', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('PhoneNumber', models.CharField(max_length=12, null=True)),
                ('Username', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
