# Generated by Django 3.2.8 on 2021-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_airplane_book_holiday_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='Data',
            field=models.DateField(default=0.00018142833580735607),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='Pornire',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
